name: Create Release
description: Create a release using GitHub CLI

inputs:
  GITHUB_TOKEN:
    description: A valid GitHub token that allow for creation of releases
    required: true

runs:
  using: composite

  steps:

    # https://cli.github.com/manual/gh_release_create
    - name: Create Release
      if: github.ref == 'refs/heads/main'
      shell: bash
      run: |
        tag=$(git tag -l | sort -V | tail -n 1)
        gh release create $tag -F changelog.md -t $tag
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

