name: Create Tag
description: Create and push a new tag

outputs:
  tag:
    description: The newly created version tag
    value: ${{ steps.tag.outputs.tag }}

runs:
  using: composite

  steps:

    # https://gitversion.net/docs/usage/cli/arguments
    - name: Create Tag
      if: github.ref == 'refs/heads/main'
      id: tag
      shell: bash
      run: |
        nextVersion=$(docker run --rm -v $(pwd):/repo gittools/gitversion:6.4.0-alpine.3.21-9.0 /repo /showvariable MajorMinorPatch)
        git tag $nextVersion
        git push --tags
        echo "tag=$nextVersion" >> $GITHUB_OUTPUT

