name: Actionlint

on:
  push:
    branches:
      - "**"

jobs:
  actionlint:
    name: Actionlint
    runs-on: ubuntu-latest

    steps:
      - name: Actionlint
        id: actionlint
        uses: raven-actions/actionlint@v2
